name: Hello-World

on:
  issues:
    types:
      - opened
      - edited
      - closed
  pull_request:
    types:
      - ready_for_review
  gollum:
  schedule:
    - cron: '42 23 1 * *'
  workflow_dispatch:
    
jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Print Hello, world! Today is {date}
        run: echo "Hello, world! Today is " & date %d-%m-%y %H:%M:%S
