name: runner

on:
  workflow_dispatch:
  
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: lsb_release

  macos:
    runs-on: macos-latest
    steps:
      - run: sw_vers -productVersion

  windows:
    runs-on: windows-latest
    steps:
      - run: Get-ComputerInfo -Property "OsVersion"
